import logging
from dataclasses import dataclass
from typing import Final

from homeassistant.components.number import (
    DEFAULT_STEP,
    NumberDeviceClass,
    NumberEntity,
    NumberEntityDescription,
    NumberMode,
)
from homeassistant.const import PERCENTAGE, UnitOfTemperature, UnitOfTime
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from custom_components.waterkotte_heatpump.pywaterkotte_ha.tags import WKHPTag
from .coordinator import WaterkotteConfigEntry
from .const import FEATURE_DISINFECTION, FEATURE_HEATING_CURVE, FEATURE_POOL, FEATURE_VENT, FIFTH_STEP, TENTH_STEP
from .entity import WKHPBaseEntity, WKHPEntityDescription

_LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True, kw_only=True)
class ExtNumberEntityDescription(WKHPEntityDescription, NumberEntityDescription):
    """The description of an entity of the platform (with the tag of the heat pump)."""


NUMBER_SENSORS: Final = [
    # temperature sensors
    # not sure if this RETURN temperature should be set able at all?!
    ExtNumberEntityDescription(
        key="TEMPERATURE_RETURN_SETPOINT",
        tag=WKHPTag.TEMPERATURE_RETURN_SETPOINT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # Cooling/Kuehlung...
    # A109
    ExtNumberEntityDescription(
        key="TEMPERATURE_COOLING_SETPOINT",
        tag=WKHPTag.TEMPERATURE_COOLING_SETPOINT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=26,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # A108
    ExtNumberEntityDescription(
        key="TEMPERATURE_COOLING_OUTDOOR_LIMIT",
        tag=WKHPTag.TEMPERATURE_COOLING_OUTDOOR_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=7,
        native_max_value=30,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # A110
    ExtNumberEntityDescription(
        key="TEMPERATURE_COOLING_FLOW_LIMIT",
        tag=WKHPTag.TEMPERATURE_COOLING_FLOW_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=4,
        native_max_value=20,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),

    # Heizung
    # A32 manual heat-setpoint (when heat_mode = 1)
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_SETPOINT",
        tag=WKHPTag.TEMPERATURE_HEATING_SETPOINT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=15,
        native_max_value=60,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_ADJUST",
        tag=WKHPTag.TEMPERATURE_HEATING_ADJUST,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=-2,
        native_max_value=2,
        native_step=FIFTH_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_HYSTERESIS",
        tag=WKHPTag.TEMPERATURE_HEATING_HYSTERESIS,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=0,
        native_max_value=10,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_ADJUST",
        tag=WKHPTag.TEMPERATURE_MIX1_ADJUST,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=-2,
        native_max_value=2,
        native_step=FIFTH_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_ADJUST",
        tag=WKHPTag.TEMPERATURE_MIX2_ADJUST,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-2,
        native_max_value=2,
        native_step=FIFTH_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_ADJUST",
        tag=WKHPTag.TEMPERATURE_MIX3_ADJUST,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-2,
        native_max_value=2,
        native_step=FIFTH_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_ADJUST",
        tag=WKHPTag.TEMPERATURE_POOL_ADJUST,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-2,
        native_max_value=2,
        native_step=FIFTH_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        feature=FEATURE_POOL
    ),
    # Heizung - Heizkennlinie
    # A93
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_HC_LIMIT",
        tag=WKHPTag.TEMPERATURE_HEATING_HC_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=35,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A94
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_HC_TARGET",
        tag=WKHPTag.TEMPERATURE_HEATING_HC_TARGET,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=65,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A91
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_HC_OUTDOOR_NORM",
        tag=WKHPTag.TEMPERATURE_HEATING_HC_OUTDOOR_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-99,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A92
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_HC_NORM",
        tag=WKHPTag.TEMPERATURE_HEATING_HC_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A95
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_SETPOINTLIMIT_MAX",
        tag=WKHPTag.TEMPERATURE_HEATING_SETPOINTLIMIT_MAX,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # A104
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_SETPOINTLIMIT_MIN",
        tag=WKHPTag.TEMPERATURE_HEATING_SETPOINTLIMIT_MIN,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # A38 - Warmwasser
    ExtNumberEntityDescription(
        key="TEMPERATURE_WATER_SETPOINT",
        tag=WKHPTag.TEMPERATURE_WATER_SETPOINT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=28,
        native_max_value=70,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_WATER_HYSTERESIS",
        tag=WKHPTag.TEMPERATURE_WATER_HYSTERESIS,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=True,
        native_min_value=0,
        native_max_value=10,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    # Mischerkreis 1 Heizkennlinie
    # A276
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_HC_LIMIT",
        tag=WKHPTag.TEMPERATURE_MIX1_HC_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=35,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A277
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_HC_TARGET",
        tag=WKHPTag.TEMPERATURE_MIX1_HC_TARGET,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=65,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A274
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_HC_OUTDOOR_NORM",
        tag=WKHPTag.TEMPERATURE_MIX1_HC_OUTDOOR_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-99,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A275
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_HC_HEATING_NORM",
        tag=WKHPTag.TEMPERATURE_MIX1_HC_HEATING_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_HEATING_CURVE
    ),
    # A278
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX1_HC_MAX",
        tag=WKHPTag.TEMPERATURE_MIX1_HC_MAX,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=72,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # Mischerkreis 2 Heizkennlinie
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_HC_LIMIT",
        tag=WKHPTag.TEMPERATURE_MIX2_HC_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=35,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_HC_TARGET",
        tag=WKHPTag.TEMPERATURE_MIX2_HC_TARGET,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=65,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_HC_OUTDOOR_NORM",
        tag=WKHPTag.TEMPERATURE_MIX2_HC_OUTDOOR_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-99,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_HC_HEATING_NORM",
        tag=WKHPTag.TEMPERATURE_MIX2_HC_HEATING_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX2_HC_MAX",
        tag=WKHPTag.TEMPERATURE_MIX2_HC_MAX,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=72,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # Mischerkreis 3 Heizkennlinie
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_HC_LIMIT",
        tag=WKHPTag.TEMPERATURE_MIX3_HC_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=35,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_HC_TARGET",
        tag=WKHPTag.TEMPERATURE_MIX3_HC_TARGET,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=65,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_HC_OUTDOOR_NORM",
        tag=WKHPTag.TEMPERATURE_MIX3_HC_OUTDOOR_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-99,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_HC_HEATING_NORM",
        tag=WKHPTag.TEMPERATURE_MIX3_HC_HEATING_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_MIX3_HC_MAX",
        tag=WKHPTag.TEMPERATURE_MIX3_HC_MAX,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=72,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    # Pool-Temperature Setpoint's
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_SETPOINT",
        tag=WKHPTag.TEMPERATURE_POOL_SETPOINT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=75,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_POOL
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_HYSTERESIS",
        tag=WKHPTag.TEMPERATURE_POOL_HYSTERESIS,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=10,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        feature=FEATURE_POOL
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_HC_LIMIT",
        tag=WKHPTag.TEMPERATURE_POOL_HC_LIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=35,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_POOL
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_HC_TARGET",
        tag=WKHPTag.TEMPERATURE_POOL_HC_TARGET,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=65,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_POOL
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_HC_OUTDOOR_NORM",
        tag=WKHPTag.TEMPERATURE_POOL_HC_OUTDOOR_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-99,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_POOL
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_HC_NORM",
        tag=WKHPTag.TEMPERATURE_POOL_HC_NORM,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_POOL
    ),
    # Water disinfection start time & duration -> weekdays will be set in
    # switch.py
    ExtNumberEntityDescription(
        key="TEMPERATURE_WATER_DISINFECTION",
        tag=WKHPTag.TEMPERATURE_WATER_DISINFECTION,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=60,
        native_max_value=70,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        feature=FEATURE_DISINFECTION
    ),
    ExtNumberEntityDescription(
        key="SCHEDULE_WATER_DISINFECTION_DURATION",
        tag=WKHPTag.SCHEDULE_WATER_DISINFECTION_DURATION,
        device_class=None,  # duration in h
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=23,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=UnitOfTime.HOURS,
        feature=FEATURE_DISINFECTION
    ),
    ExtNumberEntityDescription(
        key="BASICVENT_INCOMING_FAN_MANUAL_SPEED_PERCENT",
        tag=WKHPTag.BASICVENT_INCOMING_FAN_MANUAL_SPEED_PERCENT,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
        feature=FEATURE_VENT
    ),
    ExtNumberEntityDescription(
        key="BASICVENT_OUTGOING_FAN_MANUAL_SPEED_PERCENT",
        tag=WKHPTag.BASICVENT_OUTGOING_FAN_MANUAL_SPEED_PERCENT,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
        feature=FEATURE_VENT
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_POWLIMIT_MIN",
        tag=WKHPTag.TEMPERATURE_HEATING_POWLIMIT_MIN,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_HEATING_POWLIMIT_MAX",
        tag=WKHPTag.TEMPERATURE_HEATING_POWLIMIT_MAX,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_WATER_POWLIMIT_MIN",
        tag=WKHPTag.TEMPERATURE_WATER_POWLIMIT_MIN,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_WATER_POWLIMIT_MAX",
        tag=WKHPTag.TEMPERATURE_WATER_POWLIMIT_MAX,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_POWLIMIT_MIN",
        tag=WKHPTag.TEMPERATURE_POOL_POWLIMIT_MIN,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_POWLIMIT_MAX",
        tag=WKHPTag.TEMPERATURE_POOL_POWLIMIT_MAX,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_SETPOINTLIMIT",
        tag=WKHPTag.TEMPERATURE_POOL_SETPOINTLIMIT,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=99,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_POOL_MAX_RUNTIME",
        tag=WKHPTag.TEMPERATURE_POOL_MAX_RUNTIME,
        device_class=NumberDeviceClass.DURATION,
        entity_registry_enabled_default=False,
        native_min_value=5,
        native_max_value=180,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTime.MINUTES
    ),


    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_PRE_RUNTIME_I1278",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_PRE_RUNTIME_I1278,
        device_class=NumberDeviceClass.DURATION,
        entity_registry_enabled_default=False,
        native_min_value=25,
        native_max_value=500,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTime.SECONDS
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_POST_RUNTIME_I1279",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_POST_RUNTIME_I1279,
        device_class=NumberDeviceClass.DURATION,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=500,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTime.SECONDS
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_ANTI_JAMMING_I1280",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_ANTI_JAMMING_I1280,
        device_class=NumberDeviceClass.DURATION,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=500,
        native_step=DEFAULT_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTime.SECONDS
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_TEMP_ON_LOWER_A1539",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_TEMP_ON_LOWER_A1539,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=-50,
        native_max_value=50,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_HEATMODE_MINSPEED_A485",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_HEATMODE_MINSPEED_A485,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_HEATMODE_MAXSPEED_A486",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_HEATMODE_MAXSPEED_A486,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_HEATMODE_SOURCE_TEMPERATURE_A479",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_HEATMODE_SOURCE_TEMPERATURE_A479,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=40,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_COOLINGMODE_MINSPEED_A1032",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_COOLINGMODE_MINSPEED_A1032,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_COOLINGMODE_MAXSPEED_A1033",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_COOLINGMODE_MAXSPEED_A1033,
        device_class=None,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=100,
        native_step=DEFAULT_STEP,
        mode=NumberMode.SLIDER,
        native_unit_of_measurement=PERCENTAGE,
    ),
    ExtNumberEntityDescription(
        key="PUMPSERVICE_SOURCEPUMP_COOLINGMODE_SOURCE_TEMPERATURE_A1034",
        tag=WKHPTag.PUMPSERVICE_SOURCEPUMP_COOLINGMODE_SOURCE_TEMPERATURE_A1034,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=0,
        native_max_value=50,
        native_step=TENTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
    ExtNumberEntityDescription(
        key="TEMPERATURE_ROOM_TARGET_A100",
        tag=WKHPTag.TEMPERATURE_ROOM_TARGET_A100,
        device_class=NumberDeviceClass.TEMPERATURE,
        entity_registry_enabled_default=False,
        native_min_value=15,
        native_max_value=30,
        native_step=FIFTH_STEP,
        mode=NumberMode.BOX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
    ),
]



async def async_setup_entry(hass: HomeAssistant, config_entry: WaterkotteConfigEntry,
                            async_add_entities: AddConfigEntryEntitiesCallback):
    _LOGGER.debug("NUMBER async_setup_entry")
    coordinator = config_entry.runtime_data
    async_add_entities(WKHPNumber(coordinator, description) for description in NUMBER_SENSORS)


class WKHPNumber(WKHPBaseEntity, NumberEntity):

    @property
    def native_value(self) -> float | None:
        value = self._tag_value
        try:
            return None if value is None else float(value)
        except (TypeError, ValueError):
            return None

    async def async_set_native_value(self, value: float) -> None:
        # the tag converts the value (e.g. an adjustment to its index) - an invalid value is raised
        await self.coordinator.async_write_tag(self.wkhp_tag, value)
