import logging
from dataclasses import dataclass
from datetime import datetime, time
from typing import Final

from homeassistant.components.sensor import SensorDeviceClass, SensorEntity, SensorEntityDescription, SensorStateClass
from homeassistant.const import (
    EntityCategory,
    PERCENTAGE,
    REVOLUTIONS_PER_MINUTE,
    UnitOfDensity,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfPressure,
    UnitOfRatio,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback
from homeassistant.util import dt as dt_util

from custom_components.waterkotte_heatpump.pywaterkotte_ha.tags import WKHPTag
from .coordinator import WaterkotteConfigEntry
from .const import FEATURE_DISINFECTION, FEATURE_POOL, FEATURE_VENT
from .entity import WKHPBaseEntity, WKHPEntityDescription

_LOGGER = logging.getLogger(__name__)

# the entities are updated by the coordinator
PARALLEL_UPDATES = 0


@dataclass(frozen=True, kw_only=True)
class ExtSensorEntityDescription(WKHPEntityDescription, SensorEntityDescription):
    """The description of an entity of the platform (with the tag of the heat pump)."""

    # the state, when the heat pump provides an empty value (e.g. no active alarm)
    empty_value: str | None = None


SENSOR_SENSORS: Final = [
    # temperature sensors
    ExtSensorEntityDescription(
        key="TEMPERATURE_OUTSIDE",
        tag=WKHPTag.TEMPERATURE_OUTSIDE,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_OUTSIDE_1H",
        tag=WKHPTag.TEMPERATURE_OUTSIDE_1H,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_OUTSIDE_24H",
        tag=WKHPTag.TEMPERATURE_OUTSIDE_24H,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_SOURCE_ENTRY",
        tag=WKHPTag.TEMPERATURE_SOURCE_ENTRY,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_SOURCE_EXIT",
        tag=WKHPTag.TEMPERATURE_SOURCE_EXIT,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_EVAPORATION",
        tag=WKHPTag.TEMPERATURE_EVAPORATION,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_SUCTION_LINE",
        tag=WKHPTag.TEMPERATURE_SUCTION_LINE,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_RETURN",
        tag=WKHPTag.TEMPERATURE_RETURN,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_FLOW",
        tag=WKHPTag.TEMPERATURE_FLOW,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_CONDENSATION",
        tag=WKHPTag.TEMPERATURE_CONDENSATION,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_BUFFERTANK",
        tag=WKHPTag.TEMPERATURE_BUFFERTANK,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_ROOM",
        tag=WKHPTag.TEMPERATURE_ROOM,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_ROOM_1H",
        tag=WKHPTag.TEMPERATURE_ROOM_1H,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_HEATING",
        tag=WKHPTag.TEMPERATURE_HEATING,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_HEATING_DEMAND",
        tag=WKHPTag.TEMPERATURE_HEATING_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_COOLING",
        tag=WKHPTag.TEMPERATURE_COOLING,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_COOLING_DEMAND",
        tag=WKHPTag.TEMPERATURE_COOLING_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_WATER",
        tag=WKHPTag.TEMPERATURE_WATER,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_WATER_DEMAND",
        tag=WKHPTag.TEMPERATURE_WATER_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX1",
        tag=WKHPTag.TEMPERATURE_MIX1,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX1_PERCENT",
        tag=WKHPTag.TEMPERATURE_MIX1_PERCENT,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX1_DEMAND",
        tag=WKHPTag.TEMPERATURE_MIX1_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX2",
        tag=WKHPTag.TEMPERATURE_MIX2,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX2_PERCENT",
        tag=WKHPTag.TEMPERATURE_MIX2_PERCENT,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX2_DEMAND",
        tag=WKHPTag.TEMPERATURE_MIX2_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX3",
        tag=WKHPTag.TEMPERATURE_MIX3,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX3_PERCENT",
        tag=WKHPTag.TEMPERATURE_MIX3_PERCENT,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_MIX3_DEMAND",
        tag=WKHPTag.TEMPERATURE_MIX3_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_POOL",
        tag=WKHPTag.TEMPERATURE_POOL,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        feature=FEATURE_POOL
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_POOL_DEMAND",
        tag=WKHPTag.TEMPERATURE_POOL_DEMAND,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        feature=FEATURE_POOL
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_SOLAR",
        tag=WKHPTag.TEMPERATURE_SOLAR,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_SOLAR_EXIT",
        tag=WKHPTag.TEMPERATURE_SOLAR_EXIT,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_DISCHARGE",
        tag=WKHPTag.TEMPERATURE_DISCHARGE,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    # other (none temperature) values...
    ExtSensorEntityDescription(
        key="PRESSURE_EVAPORATION",
        tag=WKHPTag.PRESSURE_EVAPORATION,
        device_class=SensorDeviceClass.PRESSURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPressure.BAR,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="PRESSURE_CONDENSATION",
        tag=WKHPTag.PRESSURE_CONDENSATION,
        device_class=SensorDeviceClass.PRESSURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPressure.BAR,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="PRESSURE_WATER",
        tag=WKHPTag.PRESSURE_WATER,
        device_class=SensorDeviceClass.PRESSURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPressure.BAR,
        entity_registry_enabled_default=False
    ),
    # other data...
    ExtSensorEntityDescription(
        key="POSITION_EXPANSION_VALVE",
        tag=WKHPTag.POSITION_EXPANSION_VALVE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="SUCTION_GAS_OVERHEATING",
        tag=WKHPTag.SUCTION_GAS_OVERHEATING,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="POWER_ELECTRIC",
        tag=WKHPTag.POWER_ELECTRIC,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="POWER_HEATING",
        tag=WKHPTag.POWER_HEATING,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="POWER_COOLING",
        tag=WKHPTag.POWER_COOLING,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="COP_HEATING",
        tag=WKHPTag.COP_HEATING,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="COP_COOLING",
        tag=WKHPTag.COP_COOLING,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="ENERGY_CONSUMPTION_TOTAL_YEAR",
        tag=WKHPTag.ENERGY_CONSUMPTION_TOTAL_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="COMPRESSOR_ELECTRIC_CONSUMPTION_YEAR",
        tag=WKHPTag.COMPRESSOR_ELECTRIC_CONSUMPTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="SOURCEPUMP_ELECTRIC_CONSUMPTION_YEAR",
        tag=WKHPTag.SOURCEPUMP_ELECTRIC_CONSUMPTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=False,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="ELECTRICAL_HEATER_ELECTRIC_CONSUMPTION_YEAR",
        tag=WKHPTag.ELECTRICAL_HEATER_ELECTRIC_CONSUMPTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="ENERGY_PRODUCTION_TOTAL_YEAR",
        tag=WKHPTag.ENERGY_PRODUCTION_TOTAL_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="HEATING_ENERGY_PRODUCTION_YEAR",
        tag=WKHPTag.HEATING_ENERGY_PRODUCTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="HOT_WATER_ENERGY_PRODUCTION_YEAR",
        tag=WKHPTag.HOT_WATER_ENERGY_PRODUCTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="POOL_ENERGY_PRODUCTION_YEAR",
        tag=WKHPTag.POOL_ENERGY_PRODUCTION_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=False,
        suggested_display_precision=3,
        feature=FEATURE_POOL
    ),
    ExtSensorEntityDescription(
        key="COOLING_ENERGY_YEAR",
        tag=WKHPTag.COOLING_ENERGY_YEAR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=True,
        suggested_display_precision=3
    ),
    ExtSensorEntityDescription(
        key="PERCENT_HEAT_CIRC_PUMP",
        tag=WKHPTag.PERCENT_HEAT_CIRC_PUMP,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="PERCENT_SOURCE_PUMP",
        tag=WKHPTag.PERCENT_SOURCE_PUMP,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="PERCENT_COMPRESSOR",
        tag=WKHPTag.PERCENT_COMPRESSOR,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="WATERKOTTE_BIOS_TIME",
        tag=WKHPTag.WATERKOTTE_BIOS_TIME,
        device_class=SensorDeviceClass.TIMESTAMP,
        state_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="HOLIDAY_START_TIME",
        tag=WKHPTag.HOLIDAY_START_TIME,
        device_class=SensorDeviceClass.TIMESTAMP,
        state_class=None,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="HOLIDAY_END_TIME",
        tag=WKHPTag.HOLIDAY_END_TIME,
        device_class=SensorDeviceClass.TIMESTAMP,
        state_class=None,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="SCHEDULE_WATER_DISINFECTION_START_TIME",
        tag=WKHPTag.SCHEDULE_WATER_DISINFECTION_START_TIME,
        device_class=None,
        state_class=None,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=False,
        feature=FEATURE_DISINFECTION
    ),
    ExtSensorEntityDescription(
        key="STATE_SERVICE",
        tag=WKHPTag.STATE_SERVICE,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=None,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="ALARM_BITS",
        tag=WKHPTag.ALARM_BITS,
        empty_value="none",
        device_class=None,
        state_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=True
    ),
    ExtSensorEntityDescription(
        key="INTERRUPTION_BITS",
        tag=WKHPTag.INTERRUPTION_BITS,
        empty_value="none",
        device_class=None,
        state_class=None,
        native_unit_of_measurement=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=True
    ),

    ExtSensorEntityDescription(
        key="BASICVENT_TEMPERATURE_OUTGOING_AIR_BEFORE_ETH_A4998",
        tag=WKHPTag.BASICVENT_TEMPERATURE_OUTGOING_AIR_BEFORE_ETH_A4998,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_TEMPERATURE_OUTGOING_AIR_AFTER_EEH_A4994",
        tag=WKHPTag.BASICVENT_TEMPERATURE_OUTGOING_AIR_AFTER_EEH_A4994,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_TEMPERATURE_INCOMING_AIR_BEFORE_ODA_A5000",
        tag=WKHPTag.BASICVENT_TEMPERATURE_INCOMING_AIR_BEFORE_ODA_A5000,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_TEMPERATURE_INCOMING_AIR_AFTER_SUP_A4996",
        tag=WKHPTag.BASICVENT_TEMPERATURE_INCOMING_AIR_AFTER_SUP_A4996,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_FILTER_CHANGE_OPERATING_DAYS_A4498",
        tag=WKHPTag.BASICVENT_FILTER_CHANGE_OPERATING_DAYS_A4498,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTime.DAYS,
        unit_of_measurement=UnitOfTime.DAYS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_FILTER_CHANGE_REMAINING_OPERATING_DAYS_A4504",
        tag=WKHPTag.BASICVENT_FILTER_CHANGE_REMAINING_OPERATING_DAYS_A4504,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTime.DAYS,
        unit_of_measurement=UnitOfTime.DAYS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_HUMIDITY_VALUE_A4990",
        tag=WKHPTag.BASICVENT_HUMIDITY_VALUE_A4990,
        device_class=SensorDeviceClass.HUMIDITY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_CO2_VALUE_A4992",
        tag=WKHPTag.BASICVENT_CO2_VALUE_A4992,
        device_class=SensorDeviceClass.CO2,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfRatio.PARTS_PER_MILLION,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_VOC_VALUE_A4522",
        tag=WKHPTag.BASICVENT_VOC_VALUE_A4522,
        device_class=SensorDeviceClass.VOLATILE_ORGANIC_COMPOUNDS,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfDensity.MICROGRAMS_PER_CUBIC_METER,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_INCOMING_FAN_RPM_A4551",
        tag=WKHPTag.BASICVENT_INCOMING_FAN_RPM_A4551,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_INCOMING_FAN_A4986",
        tag=WKHPTag.BASICVENT_INCOMING_FAN_A4986,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_OUTGOING_FAN_RPM_A4547",
        tag=WKHPTag.BASICVENT_OUTGOING_FAN_RPM_A4547,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=REVOLUTIONS_PER_MINUTE,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_OUTGOING_FAN_A4984",
        tag=WKHPTag.BASICVENT_OUTGOING_FAN_A4984,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_ENERGY_SAVE_TOTAL_A4387",
        tag=WKHPTag.BASICVENT_ENERGY_SAVE_TOTAL_A4387,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_ENERGY_SAVE_CURRENT_A4389",
        tag=WKHPTag.BASICVENT_ENERGY_SAVE_CURRENT_A4389,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfPower.WATT,
        entity_registry_enabled_default=False,
        suggested_display_precision=2,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="BASICVENT_ENERGY_RECOVERY_RATE_A4391",
        tag=WKHPTag.BASICVENT_ENERGY_RECOVERY_RATE_A4391,
        device_class=None,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=PERCENTAGE,
        entity_registry_enabled_default=False,
        suggested_display_precision=1,
        feature=FEATURE_VENT
    ),
    ExtSensorEntityDescription(
        key="TEMPERATURE_ROOM_1H_A98",
        tag=WKHPTag.TEMPERATURE_ROOM_1H_A98,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_SOLAR",
        tag=WKHPTag.OPERATING_HOURS_SOLAR,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_COMPRESSOR_1",
        tag=WKHPTag.OPERATING_HOURS_COMPRESSOR_1,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_COMPRESSOR_2",
        tag=WKHPTag.OPERATING_HOURS_COMPRESSOR_2,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_CIRCULATION_PUMP",
        tag=WKHPTag.OPERATING_HOURS_CIRCULATION_PUMP,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_SOURCE_PUMP",
        tag=WKHPTag.OPERATING_HOURS_SOURCE_PUMP,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        suggested_display_precision=0,
    ),

    # new OPERATING_HOURS Sensors (all disabled by default)
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_COMPRESSOR_1_A516",
        tag=WKHPTag.OPERATING_HOURS_V2_COMPRESSOR_1_A516,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_COMPRESSOR_2_A518",
        tag=WKHPTag.OPERATING_HOURS_V2_COMPRESSOR_2_A518,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_FULL_OPERATING_HOURS_A520",
        tag=WKHPTag.OPERATING_HOURS_V2_FULL_OPERATING_HOURS_A520,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HEATINGPUMP_A522",
        tag=WKHPTag.OPERATING_HOURS_V2_HEATINGPUMP_A522,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_SOURCE_PUMP_A524",
        tag=WKHPTag.OPERATING_HOURS_V2_SOURCE_PUMP_A524,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_SOLAR_CIRCULATION_PUMP_A526",
        tag=WKHPTag.OPERATING_HOURS_V2_SOLAR_CIRCULATION_PUMP_A526,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_EXTERNALHEATER_A528",
        tag=WKHPTag.OPERATING_HOURS_V2_EXTERNALHEATER_A528,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HEATING_A530",
        tag=WKHPTag.OPERATING_HOURS_V2_HEATING_A530,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_COOLING_A532",
        tag=WKHPTag.OPERATING_HOURS_V2_COOLING_A532,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HOT_WATER_A534",
        tag=WKHPTag.OPERATING_HOURS_V2_HOT_WATER_A534,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=True,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_POOL_HEATING_A536",
        tag=WKHPTag.OPERATING_HOURS_V2_POOL_HEATING_A536,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_SOLAR_A538",
        tag=WKHPTag.OPERATING_HOURS_V2_SOLAR_A538,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_FUNCTIONAL_HEATING_A540",
        tag=WKHPTag.OPERATING_HOURS_V2_FUNCTIONAL_HEATING_A540,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_DEFROSTER_A542",
        tag=WKHPTag.OPERATING_HOURS_V2_DEFROSTER_A542,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_BIVALENT_PARALLEL_A544",
        tag=WKHPTag.OPERATING_HOURS_V2_BIVALENT_PARALLEL_A544,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_BIVALENT_ALTERNATIVE_A546",
        tag=WKHPTag.OPERATING_HOURS_V2_BIVALENT_ALTERNATIVE_A546,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_PV_YIELD_ALT_A576",
        tag=WKHPTag.OPERATING_HOURS_V2_PV_YIELD_ALT_A576,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_PV_YIELD_A963",
        tag=WKHPTag.OPERATING_HOURS_V2_PV_YIELD_A963,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_COMPRESSOR_3_A706",
        tag=WKHPTag.OPERATING_HOURS_V2_COMPRESSOR_3_A706,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_COMPRESSOR_4_A708",
        tag=WKHPTag.OPERATING_HOURS_V2_COMPRESSOR_4_A708,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_DEFROSTER_2_A710",
        tag=WKHPTag.OPERATING_HOURS_V2_DEFROSTER_2_A710,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_DEFROSTER_3_A712",
        tag=WKHPTag.OPERATING_HOURS_V2_DEFROSTER_3_A712,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_DEFROSTER_4_A714",
        tag=WKHPTag.OPERATING_HOURS_V2_DEFROSTER_4_A714,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HEATINGPUMP_2_A716",
        tag=WKHPTag.OPERATING_HOURS_V2_HEATINGPUMP_2_A716,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HEATINGPUMP_3_A718",
        tag=WKHPTag.OPERATING_HOURS_V2_HEATINGPUMP_3_A718,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    ExtSensorEntityDescription(
        key="OPERATING_HOURS_V2_HEATINGPUMP_4_A720",
        tag=WKHPTag.OPERATING_HOURS_V2_HEATINGPUMP_4_A720,
        device_class=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    )
]



async def async_setup_entry(hass: HomeAssistant, config_entry: WaterkotteConfigEntry,
                            async_add_entities: AddConfigEntryEntitiesCallback):
    _LOGGER.debug("SENSOR async_setup_entry")
    coordinator = config_entry.runtime_data
    async_add_entities(WKHPSensor(coordinator, description) for description in SENSOR_SENSORS)


class WKHPSensor(WKHPBaseEntity, SensorEntity):

    @property
    def native_value(self):
        """Return the state of the sensor."""
        value = self._tag_value
        if value is None:
            return self.entity_description.empty_value
        if isinstance(value, datetime):
            # the heat pump provides the local time (SensorDeviceClass.TIMESTAMP requires the time zone)
            return value.replace(tzinfo=dt_util.get_default_time_zone())
        if isinstance(value, time):
            return value.isoformat(timespec="minutes")
        if isinstance(value, bool):
            return "on" if value else "off"
        return value
