set_holiday:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: waterkotte_heatpump
    start:
      required: true
      selector:
        datetime:
    end:
      required: true
      selector:
        datetime:

set_disinfection_start_time:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: waterkotte_heatpump
    starthhmm:
      required: true
      selector:
        time:

get_energy_balance:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: waterkotte_heatpump

get_energy_balance_monthly:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: waterkotte_heatpump
